services:
  - type: web
    name: inventapro-familiar
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: inventario-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
